version: 0.0
os: windows
files:
  - source: \publish
    destination: C:\SampleProject
    overwrite: merge

hooks:
  AfterInstall:
    - location: publish\CompareAndCopyfiles.ps1
      runas: Administrator
      timeout: 300
