version: 0.0
os: windows
files:
  - source: /
    destination: C:\SQLScripts\FromGitHub
    overwrite: true
hooks:
  AfterInstall:
    - location: powershell.exe
      runas: Administrator
      args: -ExecutionPolicy Bypass -File C:\\SQLScripts\\FromGitHub\\psupdatescript.ps1
