version: 0.2

phases:
  install:
    commands:
      - git fetch --all
      - dotnet restore NetCoreHealthCheckSample.csproj

  build:
    commands:
      - dotnet build -c Release NetCoreHealthCheckSample.csproj

  post_build:
    commands:
      # Identify modified files using Git between version1 and master branches
      - git diff --name-only origin/version1...origin/master > changed_files.txt

      # Create a deployment directory
      - mkdir -p deployment

      # Copy only modified files to the deployment directory
      - xargs -I{} cp --parents {} deployment/ < changed_files.txt || true

artifacts:
  files: 
    - deployment/**/*
    - scripts/**/*
    - AppSpec.yml
