version: 0.2

phases:
  install:
    commands:
      - git diff --name-only master..Version1 > changed_files.txt || true
      - dotnet restore NetCoreHealthCheckSample.csproj
  build:
    commands:
      - dotnet build -c Release NetCoreHealthCheckSample.csproj
  post_build:
    commands:
      - |
        if [ -s changed_files.txt ]; then
          echo "Building artifact with only modified files."
          mkdir -p publish
          xargs -I {} cp {} publish/
          echo "Publishing artifact to CodeDeploy directory..."
          mkdir -p $CODEDEPLOY/deployment-archive
          mv publish/* $CODEDEPLOY/deployment-archive/
        else
          echo "No changes found. Skipping artifact creation."
          exit 0
        fi
artifacts:
  files:
    - publish/**/*
    - scripts/**/*
    - AppSpec.yml
    - changed_files.txt
