version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build -c Release
      - dotnet publish -c Release -o ./publish/controllers NetCoreHealthCheckSample/controllers/controllers.csproj
      - dotnet publish -c Release -o ./publish/extensions/HealthChecks NetCoreHealthCheckSample/extensions/HealthChecks/HealthChecks.csproj
  post_build:
    commands:
      - mkdir -p ./build-output/controllers
      - mkdir -p ./build-output/extensions/HealthChecks
      - cp -R ./publish/controllers/* ./build-output/controllers/
      - cp -R ./publish/extensions/HealthChecks/* ./build-output/extensions/HealthChecks/
artifacts:
  files:
    - build-output/**
    - scripts/**/*
    - AppSpec.yml
