version: 0.2

phases:
  install:
    commands:
      - dotnet restore NetCoreHealthCheckSample.csproj
  build:
    commands:
      - dotnet build -c Release NetCoreHealthCheckSample.csproj
  post_build:
    commands:
      - git diff --name-only version1...master > changed_files.txt
      # - dotnet publish -c Release -o ./publish NetCoreHealthCheckSample.csproj
      - mkdir -p deployment
      - xargs -I{} cp --parents {} deployment/ < changed_files.txt || true
artifacts:
  files: 
    - deployment/**/*
    - scripts/**/*
    - AppSpec.yml
