name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Print current working directory
      run: |
        echo "Current working directory:"
        pwd
    - name: List contents of the workspace directory
      run: |
        echo "Contents of the workspace directory:"
        ls -R ${{ github.workspace }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ${{ github.workspace }}/bin
        
    - name: Copy artifact to EC2 instance
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -o StrictHostKeyChecking=no -r ${{ github.workspace }}/bin/* Administrator@<13.37.239.151>:C:\Git
