name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Print current working directory
      run: |
        echo "Current working directory:"
        pwd
    - name: List contents of the workspace directory
      run: |
        echo "Contents of the workspace directory:"
        ls -R ${{ github.workspace }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ${{ github.workspace }}/bin
    - name: Debug SSH Key Path
      run: |
        echo "HOME environment variable: $HOME"
        echo "SSH Key Path: $HOME/.ssh/id_rsa"
    - name: Upload artifact to Windows Server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        $sshKeyPath = "C:\\Users\\Ajay.Banala\\.ssh\\id_rsa"
        $source = "C:\\actions-runner\\_work\\SampleProject\\SampleProject\\bin\\*"
        $destination = "C:\\Packagefile"  # Use forward slashes for Windows paths
        echo "SSH Key Path: $sshKeyPath"
        echo "Source: $source"
        echo "Destination: $destination"
        ssh -i $sshKeyPath Ajay.Banala@${{ secrets.SERVER_HOST }} "mkdir -p $destination"
        scp -i $sshKeyPath -r $source admin.ajay@${{ secrets.SERVER_HOST }}:$destination
