name: CI-CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test
      run: dotnet build && dotnet test

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: zip publish
      run: Compress-Archive -Path ./publish -DestinationPath ./publish/publish.zip

    - name: Configure AWS credentials from Test account
      run: |
        echo "[default]" >> $HOME/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
        echo "region=eu-west-3" >> $HOME/.aws/config

    - name: Upload to S3
      run: | 
        aws s3 cp ./publish/publish.zip s3://codepipeline-eu-west-3-480651260932/SampleTestProject/publish.zip

    - name: Deploy to EC2 instance
      run: |
        aws deploy create-deployment --application-name AWS_DevOps_Try --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name AWS_DevOps_Try_Group --s3-location bucket=codepipeline-eu-west-3-480651260932,key=SampleTestProject/publish.zip,bundleType=zip
