name: CI-CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test
      run: dotnet build && dotnet test

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: zip publish
      run: Compress-Archive -Path ./publish -DestinationPath ./publish/publish.zip

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: {aws-region}

    - name: Upload to S3
      run: | 
        aws s3 cp ./publish s3://{bucket-name}/{folder-name}/ --recursive

    - name: Deploy to EC2 instance
      run: |
        aws deploy create-deployment --application-name {application-name} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name {deployment-group-name} --s3-location bucket={bucket-name},key={folder-name}/publish.zip,bundleType=zip
