name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Print current working directory
      run: |
        echo "Current working directory:"
        pwd
    - name: List contents of the workspace directory
      run: |
        echo "Contents of the workspace directory:"
        ls -R ${{ github.workspace }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ${{ github.workspace }}/bin
    - name: Upload artifact to Windows Server
      env:
        SERVER_HOST: ${{ secrets.WINRM_HOST }}
        SERVER_USERNAME: ${{ secrets.WINRM_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.WINRM_PASSWORD }}
      run: |
        $password = ConvertTo-SecureString -String $env:SERVER_PASSWORD -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ($env:SERVER_USERNAME, $password)
        Invoke-Command -ComputerName $env:SERVER_HOST -Credential $cred -ScriptBlock {
          param($source, $destination)
          Copy-Item -Path $source -Destination $destination -Recurse
        } -ArgumentList "${{ github.workspace }}/bin/*", "C:\SampleProject"
